Changes for PowerAPI monitoring

diff --git a/.github/workflows/gobuild.yml b/.github/workflows/gobuild.yml
--- a/.github/workflows/gobuild.yml
+++ b/.github/workflows/gobuild.yml
@@ -1,65 +1,39 @@
-#
-# Copyright (C) 2015 Red Hat, Inc.
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#         http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-#
-
-name: Go Generate Model
-
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-    paths-ignore:
-      - 'doc/**'
-      - 'ide-config/**'
-      - '**.md'
-
 concurrency:
-  # Only run once for latest commit per ref and cancel other (previous) runs.
-  group: ci-go-kubernetes-client-${{ github.ref }}
   cancel-in-progress: true
-
-permissions:
-  contents: read
-
+  group: ci-go-kubernetes-client-${{ github.ref }}
 jobs:
   generate-model:
     name: Kubernetes Model Generator Build
-    runs-on: macos-latest
+    runs-on: self-hosted
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: 1.22
-      - name: Setup Java 11
-        uses: actions/setup-java@v4
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-      - name: Generate model
-        run: make generate-model
-      - name: Check No Schema file modified
-        run: |
-          git add .
-          MODIFIED_KUBE_SCHEMA=`git status | grep -v 'validation-schema.json' | grep 'kube-schema.json\|src/generated/java' | wc -l`
-          if [ $MODIFIED_KUBE_SCHEMA -eq "0" ]; then
-            echo "No Schema files modified. Build Success.";
-          else
-            git status | grep -v 'validation-schema.json' | grep 'kube-schema.json\|src/generated/java'
-            echo "Schema files modified. Build Failure";
-            exit 1;
-          fi;
+    - continue-on-error: true
+      name: Checkout
+      uses: actions/checkout@v4
+    - continue-on-error: true
+      name: Setup Go
+      uses: actions/setup-go@v5
+      with:
+        go-version: 1.22
+    - continue-on-error: true
+      name: Setup Java 11
+      uses: actions/setup-java@v4
+      with:
+        distribution: temurin
+        java-version: '17'
+    - continue-on-error: true
+      name: Generate model
+      run: make generate-model
+    - continue-on-error: true
+      name: Check No Schema file modified
+      run: "git add .\nMODIFIED_KUBE_SCHEMA=`git status | grep -v 'validation-schema.json'\
+        \ | grep 'kube-schema.json\\|src/generated/java' | wc -l`\nif [ $MODIFIED_KUBE_SCHEMA\
+        \ -eq \"0\" ]; then\n  echo \"No Schema files modified. Build Success.\";\n\
+        else\n  git status | grep -v 'validation-schema.json' | grep 'kube-schema.json\\\
+        |src/generated/java'\n  echo \"Schema files modified. Build Failure\";\n \
+        \ exit 1;\nfi;\n"
+name: Go Generate Model
+on:
+  repository_dispatch:
+    types: trigger-ga___gobuild.yml
+permissions:
+  contents: read
